Release v2.0.0.b4
danielgtaylor/python-betterproto pull request #307
Opened 2021-12-29 13:40 UTC by Gobot1234

Release planning for 2.0.0b4

Things I think should be merged before the release:
- #280
- #281
- #304
- #187
- #293

TODO:
- [ ] Make sure that the release date in the Changelog matches today's date before merging.
- [ ] Publish the draft v2.0.0-beta4 release right after merging

2021-12-29 18:13 UTC, kalzoo requested changes

2021-12-29 18:13 UTC, kalzoo commented on CHANGELOG.md
> +- Allow parsing of messages from `ByteStrings` [#266](https://github.com/danielgtaylor/python-betterproto/pull/266)
```suggestion

- **Breaking**: the minimum Python version has been bumped to `3.6.2`

- Always add `AsyncIterator` to imports if there are services [#264](https://github.com/danielgtaylor/python-betterproto/pull/264)
- Allow parsing of messages from `ByteStrings` [#266](https://github.com/danielgtaylor/python-betterproto/pull/266)

- Fix compilation of fields with name identical to their type [#294](https://github.com/danielgtaylor/python-betterproto/pull/294)
- Fix default values for enum service args [#299](https://github.com/danielgtaylor/python-betterproto/pull/299)
```

2021-12-29 18:13 UTC, kalzoo commented on CHANGELOG.md
> +- Allow parsing of messages from `ByteStrings` [#266](https://github.com/danielgtaylor/python-betterproto/pull/266)
(Trying to match the style currently in use, although no recent changes are specifically called out as breaking)

2021-12-30 02:25 UTC, kalzoo commented
Hey @Gobot1234 I'd be happy to release how it is now (thanks for the 3.10 fix!) and then we can do a quick release afterwards once the others are in. Helps get `optional` out the door and then we're piling less into one release. Thoughts?

2021-12-30 10:33 UTC, jdlourenco commented
@kalzoo releasing support for optional would be much appreciated! 👍

2021-12-30 10:44 UTC, Gobot1234 commented
@kalzoo sounds good to me

2022-01-03 18:03 UTC, kalzoo approved these changes
Thanks!

2022-01-03 18:18 UTC, merged

2022-01-03 19:03 UTC, lazytype commented
Thanks everyone!