allow override of timeout, deadline and metadata
danielgtaylor/python-betterproto pull request #352
Opened 2022-03-11 18:37 UTC by abn

This change ensures that overrides for timeout, deadline and metadata
are available as parameters for higher lever methods.

Resolves: #275

2022-03-11 23:34 UTC, Gobot1234 requested changes
I like the idea. One qeustion, why is _Metadata exported as a "private" type alias? Could you possible rename it?
Ideally the isort commits would be a separate PR.

2022-03-11 23:34 UTC, Gobot1234 commented on src/betterproto/plugin/models.py
> +            "from grpclib.metadata import Deadline as Deadline"
```suggestion
            "from grpclib.metadata import Deadline"
```
The as here shouldn't be neccesary, the type shouldn't be re-exported by the protobuf file

2022-03-12 00:46 UTC, abn commented on pyproject.toml
> +force_single_line = true
Moved to https://github.com/danielgtaylor/python-betterproto/pull/354/files#r825214260

2022-03-12 09:18 UTC, Gobot1234 commented
> @Gobot1234 I'd like to keep the isort-ing of the generated code as a separate commit on this PR as we introduce additional imports here. I'll spint out the isort for the betterproto code into another PR.

I could just merge the isort PR first right and keep the commits here and there shouldn't be any conflicts?

2022-03-12 09:21 UTC, Gobot1234 commented
> As for `_Metadata` I am reusing what was already there, seems like it is a copy of the one one from grpclib. One option would be to move it to `types.py` and make it non-private. I can do that change with this or later as a separate change.

Making _types.py public seems like a good idea to me

2022-03-13 00:58 UTC, abn commented
@Gobot1234 I ended up just making the type definitions public since it did not feel right for exposing grpclib clibe types under `betterproto.types`.

2022-03-13 11:01 UTC, Gobot1234 approved these changes

2022-03-13 22:27 UTC, cetanu approved these changes

2022-03-13 22:34 UTC, merged

2022-03-13 22:34 UTC, Gobot1234 commented
Thank you :)