Make Message.from_dict() a class method
danielgtaylor/python-betterproto pull request #476
Opened 2023-04-18 22:38 UTC by MarekPikula

## Rationale

For Pydantic dataclasses, it's impossible to initialize the model with `Message().from_dict(init_dict)` as the initializer of `Message` (in this case `pydantic.dataclasses.dataclass` initializer) performs the validation on init. `Message(**init_dict)` is also impossible, as the default Pydantic dataclass init doesn't perform the necessary casing and type transformations done by `from_dict()`.

## Solution

To minimise existing code breakage, a custom `hybridmethod` was used to implement the `from_dict()` both in the class and instance context. It can be used to have both classmethod and instance method with the same name and execute the right one depending on the context. Thus both the current `Message().from_dict(init_dict)` and `Message.from_dict(init_dict)` should work as expected. Let me know if you know a better or more standard way of implementing it (maybe something in `typing` I missed?).

## Possible breakage – up to discussion

(I think) that the only possible breakage of prior uses would be if instance-level `from_dict()` was applied to an existing instance if the instance has been modified by hand on runtime. That's because for the `meta.proto_type == TYPE_MESSAGE` the field type is checked for the schema and not for the modified instance. The same applies for `meta.proto_type == TYPE_ENUM` and `meta.map_types and meta.map_types[1] == TYPE_MESSAGE` (in the form of overwriting the entire dictionary instead of applying the modification from init dict).

The question is if these behaviours are even used by anyone (or even if they should be – to me, it looks pretty dangerous). In the case of tests, they are not (all tests pass). It is, of course, possible to revert the instance-level `from_dict()` back to the previous form with the downside of duplication of a rather convoluted piece of code (currently common in the form of `_from_dict_init()`). Please let me know what you think.

## Example usage

I currently use this fork in my project [MarekPikula/python-headscale-api](https://github.com/MarekPikula/python-headscale-api), which uses Pydantic dataclasses generated from the Headscale protobuf schema. The usage of the new `from_dict()` is in [headscale.py](https://github.com/MarekPikula/python-headscale-api/blob/v0.2.0/headscale_api/headscale.py#L214).

2023-06-04 14:01 UTC, MarekPikula commented
Hi, is there any chance to review this change? It would be brilliant if it was merged and (pre-)released, as I depend on this change in a project, which I want to release on PyPI (so I cannot use git-originating dependencies).

2023-07-11 09:27 UTC, Darkheir commented
I agree that missing a class method make it complicated to use `pydantic` models to parse raw messages.

2023-10-16 11:07 UTC, Gobot1234 requested changes
Might be nice to add support for parse as a classmethod as well with this

2023-10-16 11:07 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +        metadata = ProtoClassMetadata(cls)
This is not the correct way to work around this problem. ProtoClassMetadata should be made a cached class property.

2023-10-16 11:07 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +    def _from_dict_init(cls: Type[T], value: Mapping[str, Any]) -> Mapping[str, Any]:
```suggestion
    def _from_dict_init(cls, value: Mapping[str, Any]) -> Mapping[str, Any]:
```

2023-10-16 11:07 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +                        v = sub_cls.from_dict(value[key])
Please keep the comment

2023-10-16 11:07 UTC, Gobot1234 commented on src/betterproto/__init__.py
>          for key in value:
Please could you update this to use .items()

2023-10-16 11:07 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +
This file is starting to get very bloated, would you be able to pull this into a utils file or similar

2023-10-16 11:07 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +        self.finstance = finstance
Not sure why these are f prefixed. Please remove the prefix and name them something like owner and instance as is commonly  done with the descriptor protocol

2023-10-24 14:07 UTC, Gobot1234 commented on src/betterproto/__init__.py
>      def _betterproto(self) -> ProtoClassMetadata:
```suggestion
    def _betterproto(cls) -> ProtoClassMetadata:
```

2023-10-24 15:31 UTC, Gobot1234 approved these changes

2023-10-25 14:20 UTC, cetanu approved these changes

2023-10-25 21:20 UTC, merged