Bump version to 2.0.0b6
danielgtaylor/python-betterproto pull request #500
Opened 2023-06-05 13:25 UTC by ashwin153

2023-06-05 13:27 UTC, Gobot1234 commented
This still isn't ready for release. You'll also need to write a changelog for the beta release

2023-06-24 13:27 UTC, Gobot1234 requested changes
Apart from the general nits I'd appreciate it if you made separated fixes from additions

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Pull down the include_default_values argument to to_json [#405](https://github.com/danielgtaylor/python-betterproto/pull/405)
```suggestion
- Pull down the `include_default_values` argument to `to_json()` [#405](https://github.com/danielgtaylor/python-betterproto/pull/405)
```

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Enforce serialize_empty for repeated fields [#417](https://github.com/danielgtaylor/python-betterproto/pull/417)
```suggestion
- Fix "empty-valued" repeated fields not being serialised [#417](https://github.com/danielgtaylor/python-betterproto/pull/417)
```

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Drop support for python3.6 [#444](https://github.com/danielgtaylor/python-betterproto/pull/444)
This should be made more obvious (see how the previous release did it)

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Fix CI [#456](https://github.com/danielgtaylor/python-betterproto/pull/456)
```suggestion
```
This isn't worth mentioning in a changelog

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Add support for pydantic dataclasses [#406](https://github.com/danielgtaylor/python-betterproto/pull/406)
This might be worth bringing particular attention to as it's such a requested feature

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Widen from_dict methods to accept any Mapping [#451](https://github.com/danielgtaylor/python-betterproto/pull/451)
```suggestion
- Widen `from_dict()` to accept any `Mapping` [#451](https://github.com/danielgtaylor/python-betterproto/pull/451)
```

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Fix for [#459](https://github.com/danielgtaylor/python-betterproto/issues/459) (pydantic code gen only) [#460](https://github.com/danielgtaylor/python-betterproto/pull/460)
I don't particularly think this is worth mentioning considering it fixes something that was never publicly released but if you want to leave it in that's fine

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Fix pydantic_dataclasses reference in README [#474](https://github.com/danielgtaylor/python-betterproto/pull/474)
Feels very similar to the 2nd most recent comment

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Fix dict encoding for timezone aware datetimes [#468](https://github.com/danielgtaylor/python-betterproto/pull/468)
```suggestion
- Fix `dict` encoding for timezone-aware `datetimes` [#468](https://github.com/danielgtaylor/python-betterproto/pull/468)
```

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Replace pkg_resources with importlib [#462](https://github.com/danielgtaylor/python-betterproto/pull/462)
```suggestion
- Replace `pkg_resources` with `importlib` [#462](https://github.com/danielgtaylor/python-betterproto/pull/462)
```

2023-06-24 13:27 UTC, Gobot1234 commented on CHANGELOG.md
> +- Fix pydict serialization for optional fields [#495](https://github.com/danielgtaylor/python-betterproto/pull/495)
```suggestion
- Fix `to_pydict` serialization for optional fields [#495](https://github.com/danielgtaylor/python-betterproto/pull/495)
```

2023-06-24 19:32 UTC, Gobot1234 commented
You also need to add https://github.com/danielgtaylor/python-betterproto/commit/182aedaec4a6cfd2465a2c541e5f2485b0aadb58 and https://github.com/danielgtaylor/python-betterproto/commit/182aedaec4a6cfd2465a2c541e5f2485b0aadb58 to this (sorry)

2023-06-25 19:52 UTC, Gobot1234 requested changes
Last couple of things

2023-06-25 19:52 UTC, Gobot1234 commented on CHANGELOG.md
> +## [2.0.0b6] - 2023-06-05
```suggestion
## [2.0.0b6] - 2023-06-25
```

2023-06-25 19:52 UTC, Gobot1234 commented on CHANGELOG.md
> +- Added support for @generated marker [#382](https://github.com/danielgtaylor/python-betterproto/pull/382)
```suggestion
- Added support for `@generated` marker [#382](https://github.com/danielgtaylor/python-betterproto/pull/382)
```

2023-06-25 19:52 UTC, Gobot1234 commented on CHANGELOG.md
> +- Fix `to_pydict` serialization for optional fields [#495](https://github.com/danielgtaylor/python-betterproto/pull/495)
```suggestion
- Fix `to_pydict()` serialization for optional fields [#495](https://github.com/danielgtaylor/python-betterproto/pull/495)
```

2023-06-25 19:52 UTC, Gobot1234 commented on CHANGELOG.md
> +  and [README.md](https://github.com/danielgtaylor/python-betterproto#generating-pydantic-models) for more information.
```suggestion
- Support generating [Pydantic dataclasses](https://docs.pydantic.dev/latest/usage/dataclasses/). 
  Pydantic dataclasses are are drop-in replacement for dataclasses in the standard library that additionally supports validation. Pass `--python_betterproto_opt=pydantic_dataclasses` to enable this feature. Refer to [#406](https://github.com/danielgtaylor/python-betterproto/pull/406)
  and [README.md](https://github.com/danielgtaylor/python-betterproto#generating-pydantic-models) for more information.
```

2023-06-25 19:52 UTC, Gobot1234 reviewed
Last couple of things

2023-06-25 23:05 UTC, Gobot1234 commented on CHANGELOG.md
> +  and [README.md](https://github.com/danielgtaylor/python-betterproto#generating-pydantic-models) for more information.
```suggestion
- Support generating [Pydantic dataclasses](https://docs.pydantic.dev/latest/usage/dataclasses). 
  Pydantic dataclasses are are drop-in replacement for dataclasses in the standard library that additionally supports validation.
  Pass `--python_betterproto_opt=pydantic_dataclasses` to enable this feature.
  Refer to [#406](https://github.com/danielgtaylor/python-betterproto/pull/406)
  and [README.md](https://github.com/danielgtaylor/python-betterproto#generating-pydantic-models) for more information.
```

2023-06-25 23:06 UTC, Gobot1234 commented on CHANGELOG.md
> +- **Breaking**: the minimum Python version has been bumped to `3.7` [#444](https://github.com/danielgtaylor/python-betterproto/pull/444)
```suggestion
- **Breaking**: the minimum Python version has been bumped to `3.7` [#444](https://github.com/danielgtaylor/python-betterproto/pull/444)

- Support generating [Pydantic dataclasses](https://docs.pydantic.dev/latest/usage/dataclasses). 
  Pydantic dataclasses are are drop-in replacement for dataclasses in the standard library that additionally supports validation.
  Pass `--python_betterproto_opt=pydantic_dataclasses` to enable this feature.
  Refer to [#406](https://github.com/danielgtaylor/python-betterproto/pull/406)
  and [README.md](https://github.com/danielgtaylor/python-betterproto#generating-pydantic-models) for more information.
```

2023-06-25 23:11 UTC, Gobot1234 approved these changes

2023-06-25 23:11 UTC, Gobot1234 commented
Thank you for your work on this

2023-06-25 23:12 UTC, merged

2023-06-26 15:22 UTC, MicaelJarniac commented
Will this be released on PyPI? The latest there seems to still be `2.0.0b5`.

2023-06-26 19:11 UTC, Gobot1234 commented
The release action is currently failing cause @danielgtaylor's email isn't verified on pypi. We are working to remedy the situation

2023-06-26 19:23 UTC, danielgtaylor commented
@Gobot1234 I can take a look, sorry about that.

2023-06-26 20:20 UTC, MicaelJarniac commented
I see it's now released there. Thanks a lot!
https://pypi.org/project/betterproto/2.0.0b6/

2023-06-26 21:23 UTC, ryaminal commented
this is excellent. thanks to @ashwin153 and @Gobot1234 for the effort to get this out.