Fix parse_source_type_name
danielgtaylor/python-betterproto pull request #635
Opened 2024-10-25 13:22 UTC by AdrienVannson

## Summary

Fix https://github.com/danielgtaylor/python-betterproto/issues/562 , https://github.com/danielgtaylor/python-betterproto/issues/437

The function `parse_source_type_name` used to rely on an ad-hoc regex to work. The function failed when the package name had capital letters, since it believed that the package was actually a message.

Now, the function goes through the packages and the messages that are actually defined (no more guess) to find the right one.

I also did some small refactoring of `models.py`: `FieldCompiler` used to inherit from `MessageCompiler`, which made no sense.

The PR still lacks tests and some doc, but since it can take a while to write, I first wanted to have your point of view on this.

NOTE: I completely deleted `test_gen_ref_type.py` for now, but I plan to replace it once you agree with the content of the PR

## Checklist

- [X] If code changes were made then they have been tested.
- [X] This PR fixes an issue.

2024-11-07 03:12 UTC, Gobot1234 approved these changes

2024-11-07 03:12 UTC, Gobot1234 commented
Ping me once the tests are done

2024-11-08 13:24 UTC, AdrienVannson commented
Hello, I added some documentation, I would say that it is enough. Concerning the tests, I can't just add many simple unit tests as easily as before since the function `get_type_reference` now also takes a `PluginRequestCompiler`. However, everything should already be tester in the `import_*` input tests.

I just need to find out why the tests are failing, this is not normal since I almost changed nothing

2024-11-08 14:28 UTC, AdrienVannson commented
It was just the merge that was not performed correctly, now it should be fine

2024-11-08 15:24 UTC, Gobot1234 requested changes

2024-11-08 15:24 UTC, Gobot1234 commented on src/betterproto/plugin/models.py
> +    py_v_type: Type = None
Please change this to pass type checking

2024-11-08 15:24 UTC, Gobot1234 commented on src/betterproto/templates/header.py.j2
> +    {% for _, service in output_file.services|dictsort(by="key") %}
How come these are being sorted now?

2024-11-14 09:59 UTC, AdrienVannson commented
Note: it should be good to check if it works with Buf (apparently Buf can recompile partially a project, but this update makes the assumption that all the structure of the project is loaded.) I think it should be fine, but it might be worth checking

2025-01-05 03:56 UTC, cetanu approved these changes

2025-06-06 13:28 UTC, closed without merging