Remove placeholders
danielgtaylor/python-betterproto pull request #641
Opened 2024-11-12 17:11 UTC by AdrienVannson

## Summary

Remove PLACEHOLDER mechanism

Hello!

This is a first step in removing the `PLACEHOLDER` mechanism to greatly improve performance, make the whole code more Pythonic and simple and resolve a lot of bug. The motivation is more deeply described in https://github.com/danielgtaylor/python-betterproto/issues/631

This PR completely removes placeholder values from messages. Instead, a field . Therefore, all the message field are marked as optional and can be set to None, which is coherent with the specification (see the issue).

As a consequence, this fixes the following issues:
 - https://github.com/danielgtaylor/python-betterproto/issues/601 One-of pattern matching not supported by static type analysis tools

Before merging it, I think it would be good to finish the work in progress (at least my other PR and another fix of the generation of the comments), and release a new version with all the recent bugfixes.

## Performance

These changes also make it possible to remove the `__getattribute__` from messages. As expected, this has a great impact on the performance.

With the following messages:

```
message Test {
    bool x = 1;
    int32 y = 2;
    float z = 3;
}

message List {
    repeated Test msg = 1;
}
```

The following code takes 3.24s on my computer with the original (`master`) implementation **with** the Rust codec, and only 2s with my PR (without the Rust codec). Thus, even if the Rust codec is not supported for now, it is not a problem since the performance are better anywaY.

```python
msg = List(msg=[Test(x=bool(i % 2), y = i, z = i / 2) for i in range(100000)])
b = bytes(msg)
msg2 = List().parse(b)
assert msg == msg2
```

## Checklist

- [X] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [X] This PR fixes an issue.
- [X] This PR is a breaking change (e.g. methods or parameters removed/renamed)

2024-11-15 09:45 UTC, Gobot1234 requested changes
I do like this after more thought. Really do wish that PEP 515 happened

2024-11-15 09:45 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +            return []
use the list constructor here for better performance

2024-11-15 09:45 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +            return None
use NoneType here

2024-11-15 09:45 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +        lambda: False,
```suggestion
        bool,
```

2024-11-15 09:45 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +        number, TYPE_INT32, lambda: 0, group=group, optional=optional, repeated=repeated
```suggestion
        number, TYPE_INT32, int, group=group, optional=optional, repeated=repeated
```

2024-11-15 09:45 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +        number, TYPE_INT64, lambda: 0, group=group, optional=optional, repeated=repeated
```suggestion
        number, TYPE_INT64, int, group=group, optional=optional, repeated=repeated
```
I think you get the idea

2024-11-15 09:45 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +                                1, meta.map_types[0], default_factory=lambda: kt()
```suggestion
                                1, meta.map_types[0], default_factory=kt
```

2024-11-15 09:45 UTC, Gobot1234 commented on src/betterproto/__init__.py
> +                                2, meta.map_types[1], default_factory=lambda: vt()
```suggestion
                                2, meta.map_types[1], default_factory=vt
```

2024-11-15 12:38 UTC, AdrienVannson commented
Thanks! I applied your suggestions

2025-01-02 23:14 UTC, cetanu approved these changes

2025-01-02 23:57 UTC, Gobot1234 commented on src/betterproto/plugin/models.py
> +# TODO patch again to make field optional
Is this no longer required?

2025-01-05 18:33 UTC, AdrienVannson commented on src/betterproto/plugin/models.py
> +# TODO patch again to make field optional
I let them for now as a reminder to change something else, but I'll remove it soon (in the fork)

2025-01-05 18:34 UTC, AdrienVannson commented
Note: I already merged this PR in the forked repo https://github.com/betterproto as discussed on Discord, so it's probably not worth it to solve the merge conflicts here

2025-01-06 16:18 UTC, AdrienVannson commented on src/betterproto/plugin/models.py
> +# TODO patch again to make field optional
(done)

2025-06-06 13:28 UTC, closed without merging